=== chua-n/particle/nn/config/nn.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="nju.chuan.nn"
    xmlns="nju.chuan.nn" elementFormDefault="qualified">
    <xs:element name="nn">
        <xs:complexType>
            <xs:all>
                <xs:element name="hp" type="hyperParameter"/>
                <xs:element name="nnLayer">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded">
                            <xs:element name="fc" type="fullyConnected" minOccurs="0" maxOccurs="unbounded" />
                            <xs:element name="conv" type="convolution" minOccurs="0" maxOccurs="unbounded" />
                            <xs:element name="convT" type="convTranspose" minOccurs="0" maxOccurs="unbounded" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="hyperParameter">
        <xs:sequence>
            <xs:element name="nEpoch" type="xs:unsignedInt" />
            <xs:element name="bs" type="xs:unsignedInt" />
            <xs:element name="lr" type="xs:float" />
            <xs:element name="nLatent" type="xs:unsignedByte" minOccurs="0"/>
            <xs:element name="iterD" type="xs:unsignedInt" minOccurs="0"/>
            <xs:element name="iterG" type="xs:unsignedInt" default="1" minOccurs="0"/>
            <xs:element name="clip" type="xs:float" minOccurs="0"/>
            <xs:element name="lambda" type="xs:float" minOccurs="0"/>
            <xs:any minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fullyConnected">
        <xs:sequence>
            <xs:element name="in_features" type="xs:unsignedInt" />
            <xs:element name="out_features" type="xs:unsignedInt" />
            <xs:element name="bias" type="xs:boolean" />
            <xs:element name="normalize" type="normalization" />
            <xs:element name="activate" type="activateFunc" />
        </xs:sequence>
        <xs:attribute name="dim" type="dim" use="required" fixed="1d"/>
        <xs:attribute name="block" type="xs:string" use="optional"/>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>

    <xs:complexType name="convolution">
        <xs:sequence>
            <xs:element name="in_channels" type="xs:unsignedInt" />
            <xs:element name="out_channels" type="xs:unsignedInt" />
            <xs:element name="kernel_size" type="xs:unsignedByte" />
            <xs:element name="stride" type="xs:unsignedByte" />
            <xs:element name="padding" type="xs:unsignedByte" />
            <xs:element name="bias" type="xs:boolean" />
            <xs:element name="normalize" type="normalization" />
            <xs:element name="activate" type="activateFunc" />
        </xs:sequence>
        <xs:attribute name="dim" type="dim" use="required"/>
        <xs:attribute name="block" type="xs:string" use="optional"/>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>

    <xs:complexType name="convTranspose">
        <xs:sequence>
            <xs:element name="in_channels" type="xs:unsignedInt" />
            <xs:element name="out_channels" type="xs:unsignedInt" />
            <xs:element name="kernel_size" type="xs:unsignedByte" />
            <xs:element name="stride" type="xs:unsignedByte" />
            <xs:element name="padding" type="xs:unsignedByte" />
            <xs:element name="output_padding" type="xs:unsignedByte" default="0" />
            <xs:element name="bias" type="xs:boolean" />
            <xs:element name="normalize" type="normalization" />
            <xs:element name="activate" type="activateFunc" />
        </xs:sequence>
        <xs:attribute name="dim" type="dim" use="required"/>
        <xs:attribute name="block" type="xs:string" use="optional"/>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>

    <xs:simpleType name="normalizationBase">
        <xs:restriction base="xs:string">
            <xs:enumeration value="null"/>
            <xs:enumeration value="bn"/>
            <xs:enumeration value="ln"/>
            <xs:enumeration value="in"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="normalization">
        <xs:simpleContent>
            <xs:extension base="normalizationBase">
                <xs:attribute name="dataOutShape" type="xs:string" default="N,C,D,H,W" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="dim">
        <xs:restriction base="xs:string">
            <!-- <xs:enumeration value="null"/> -->
            <xs:enumeration value="1d"/>
            <xs:enumeration value="2d"/>
            <xs:enumeration value="3d"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="activateFuncBase">
        <xs:restriction base="xs:string">
            <xs:enumeration value="null"/>
            <xs:enumeration value="sigmoid"/>
            <xs:enumeration value="relu"/>
            <xs:enumeration value="leakyrelu"/>
            <xs:enumeration value="tanh"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="activateFunc">
        <xs:simpleContent>
            <xs:extension base="activateFuncBase">
                <xs:attribute name="param" type="xs:decimal" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== chua-n/particle/nn/config/vae.xml
<?xml version="1.0" encoding="UTF-8"?>
<nn xmlns="nn.chuan.nju"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="nn.chuan.nju ./nn.xsd">
    <hp>
        <nEpoch>200</nEpoch>
        <bs>64</bs>
        <lr>1e-3</lr>
        <nLatent>32</nLatent>
        <lambda>40</lambda>
    </hp>
    <nnLayer>
        <!-- Encoder -->
        <!-- 1 * 64 * 64 * 64 -->
        <conv dim="3d" id="1" block="Encoder">
            <in_channels>1</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>

        <!-- 16 * 32 * 32 * 32 -->
        <conv dim="3d" id="2" block="Encoder">
            <in_channels>16</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>

        <!-- 32 * 16 * 16 * 16 -->
        <conv dim="3d" id="3" block="Encoder">
            <in_channels>32</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>

        <!-- 64 * 8 * 8 * 8 -->
        <conv dim="3d" id="4" block="Encoder">
            <in_channels>64</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>

        <!-- 64 * 4 * 4 * 4 -->
        <conv dim="3d" id="5" block="Encoder">
            <in_channels>64</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>5</kernel_size>
            <stride>4</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>

        <!-- 128 * 1 * 1 * 1 -->
        <!-- <fc dim="1d" id="1" block="Encoder">
            <in_features>128</in_features>
            <out_features>32</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc>
        <fc dim="1d" id="2" block="Encoder">
            <in_features>128</in_features>
            <out_features>32</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc> -->

        <!-- Decoder -->
        <!-- nLatent * 1 * 1 * 1 -->
        <!-- <fc dim="1d" id="1" block="Decoder">
            <in_features>32</in_features>
            <out_features>128</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc> -->

        <!-- 128 * 1 * 1 * 1 -->
        <convT dim="3d" id="1" block="Decoder">
            <in_channels>128</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>5</kernel_size>
            <stride>4</stride>
            <padding>1</padding>
            <output_padding>1</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- 64 * 4 * 4 * 4 -->
        <convT dim="3d" id="2" block="Decoder">
            <in_channels>64</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <output_padding>1</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- 64 * 8 * 8 * 8 -->
        <convT dim="3d" id="3" block="Decoder">
            <in_channels>64</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <output_padding>1</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- 32 * 16 * 16 * 16 -->
        <convT dim="3d" id="4" block="Decoder">
            <in_channels>32</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <output_padding>1</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- 16 * 32 * 32 * 32 -->
        <convT dim="3d" id="5" block="Decoder">
            <in_channels>16</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>5</kernel_size>
            <stride>2</stride>
            <padding>2</padding>
            <output_padding>1</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>sigmoid</activate>
        </convT>

        <!-- 1 * 64 * 64 * 64 -->
    </nnLayer>
</nn>

=== chua-n/particle/nn/config/infogan.xml
<?xml version="1.0" encoding="UTF-8"?>
<nn xmlns="nn.chuan.nju"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="nn.chuan.nju ./nn.xsd">
    <hp>
        <nEpoch>10</nEpoch>
        <bs>64</bs>
        <lrD>0.0002</lrD>
        <lrG>0.001</lrG>
        <nNoise>54</nNoise>
        <nDisc>3</nDisc>
        <nCont>7</nCont>
        <iterD>1</iterD>
        <iterG>1</iterG>
    </hp>


    <nnLayer>
        <!-- ngf=64 -->
        <!-- ndf=64 -->

        <convT dim="3d" id="1" block="Generator">
            <in_channels>64</in_channels>
            <out_channels>512</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="2" block="Generator">
            <in_channels>512</in_channels>
            <out_channels>256</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="3" block="Generator">
            <in_channels>256</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="4" block="Generator">
            <in_channels>128</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="5" block="Generator">
            <in_channels>64</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate>sigmoid</activate>
        </convT>

        <conv dim="3d" id="1" block="Share">
            <in_channels>1</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <conv dim="3d" id="2" block="Share">
            <in_channels>64</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <conv dim="3d" id="3" block="Share">
            <in_channels>128</in_channels>
            <out_channels>256</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <conv dim="3d" id="4" block="Share">
            <in_channels>256</in_channels>
            <out_channels>512</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <conv dim="3d" id="5" block="Discriminator">
            <in_channels>512</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate>sigmoid</activate>
        </conv>

        <conv dim="3d" id="5" block="Q">
            <in_channels>512</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>leakyrelu</activate>
        </conv>

        <!-- <fc dim="1d" id="disc" block="Q">
            <in_features>128</in_features>
            <out_features>10</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc>

        <fc dim="1d" id="cont_mu" block="Q">
            <in_features>128</in_features>
            <out_features>2</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc>

        <fc dim="1d" id="cont_var" block="Q">
            <in_features>128</in_features>
            <out_features>2</out_features>
            <bias>true</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </fc> -->
    </nnLayer>
</nn>

=== chua-n/particle/nn/config/wgan_cp-16.xml
<?xml version="1.0" encoding="UTF-8"?>
<nn xmlns="nju.chuan.nn"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="nju.chuan.nn ./nn.xsd">
    <hp>
        <nEpoch>800</nEpoch>
        <bs>64</bs>
        <lr>0.00005</lr>
        <nLatent>64</nLatent>
        <iterD>1</iterD>
        <iterG>1</iterG>
        <clip>0.01</clip>
    </hp>
    <nnLayer>
        <!-- ndf=16 -->
        <!-- ngf=16 -->

        <!-- Discriminator -->
        <!-- 1 * 64 * 64 * 64 -->
        <conv dim="3d" id="1">
            <in_channels>1</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <!-- ndf * 32 * 32 * 32 -->
        <conv dim="3d" id="2">
            <in_channels>16</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <!-- (ndf * 2) * 16 * 16 * 16 -->
        <conv dim="3d" id="3">
            <in_channels>32</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <!-- (ndf * 4) * 8 * 8 * 8 -->
        <conv dim="3d" id="4">
            <in_channels>64</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate param="0.2">leakyrelu</activate>
        </conv>

        <!-- (ndf * 8) * 4 * 4 * 4 -->
        <conv dim="3d" id="5">
            <in_channels>128</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate>null</activate>
        </conv>
        <!-- 1 * 1 * 1 * 1 -->


        <!-- Generator -->
        <!-- nLatent * 1 * 1 * 1 -->
        <convT dim="3d" id="1">
            <in_channels>64</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- (ngf * 8) * 4 * 4 * 4 -->
        <convT dim="3d" id="2">
            <in_channels>128</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- (ngf * 4) * 8 * 8 * 8 -->
        <convT dim="3d" id="3">
            <in_channels>64</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- (ngf * 2) * 16 * 16 * 16 -->
        <convT dim="3d" id="4">
            <in_channels>32</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <!-- ngf * 32 * 32 * 32 -->
        <convT dim="3d" id="5">
            <in_channels>16</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate>tanh</activate>
        </convT>

        <!-- 1 * 64 * 64 * 64 -->
    </nnLayer>
</nn>

=== chua-n/particle/nn/config/threeViews.xml
<?xml version="1.0" encoding="UTF-8"?>
<nn xmlns="nju.chuan.nn"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="nju.chuan.nn ./nn.xsd">
    <hp>
        <nEpoch>60</nEpoch>
        <bs>128</bs>
        <lr>0.001</lr>
    </hp>
    <nnLayer>
        <!-- 64 * 64 -->
        <conv dim="2d" id="1">
            <in_channels>3</in_channels>
            <out_channels>8</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>
        <!-- 32 * 32 -->
        <conv dim="2d" id="2">
            <in_channels>8</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>
        <!-- 16 * 16 -->
        <conv dim="2d" id="3">
            <in_channels>16</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>
        <!-- 8 * 8 -->
        <conv dim="2d" id="4">
            <in_channels>32</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </conv>
        <!-- 4 * 4 -->
        <fc dim="1d" id="1">
            <in_features>1024</in_features>
            <out_features>256</out_features>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </fc>

        <convT dim="3d" id="1">
            <in_channels>256</in_channels>
            <out_channels>128</out_channels>
            <kernel_size>4</kernel_size>
            <stride>1</stride>
            <padding>0</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="2">
            <in_channels>128</in_channels>
            <out_channels>64</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="3">
            <in_channels>64</in_channels>
            <out_channels>32</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="4">
            <in_channels>32</in_channels>
            <out_channels>16</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>bn</normalize>
            <activate>relu</activate>
        </convT>

        <convT dim="3d" id="5">
            <in_channels>16</in_channels>
            <out_channels>1</out_channels>
            <kernel_size>4</kernel_size>
            <stride>2</stride>
            <padding>1</padding>
            <output_padding>0</output_padding>
            <bias>false</bias>
            <normalize>null</normalize>
            <activate>sigmoid</activate>
        </convT>
    </nnLayer>
</nn>
